### PR TITLE
Fix comments in config.yaml

### PR DESCRIPTION
**Pull request by zou000**

### CODE REVIEW

**Comment by arrowtype** [comment]
Oops, I should have updated those comments after adjusting the stylistic sets. 😬 Nice job figuring it out, and thank you for submitting a PR!

I'll leave it open temporarily as a reminder for myself to verify the accuracy of the stylistic set guidance in this repo overall, then merge it once I'm confident things are all correct.

**Comment by seritools** [comment]
The [predefined configs](https://github.com/arrowtype/recursive-code-config/blob/0bcd36becfc578371715ce45f7b1b2c64e5dcfda/premade-configs/duotone.yaml) also still use the old ones, meaning that the distributed releases in the main repo activate the wrong styles:

image

**Comment by arrowtype** [comment]
Thanks, @zou000 for flagging this, and thanks @seritools for commenting further.

I needed to update the stylistic set info in a few places, so I did this and built new fonts in c736d86643.

So, this PR was helpful, but I’ll close it now that things are solved. Cheers!

**Comment by arrowtype** [comment]
PS I have also updated the fonts at https://github.com/arrowtype/recursive/releases/tag/1.066.

Thanks for pointing out that specific error, @seritools!

**Comment by zou000** [comment]
> Thanks, @zou000 for flagging this, and thanks @seritools for commenting further.
> 
> I needed to update the stylistic set info in a few places, so I did this and built new fonts in [c736d86](https://github.com/arrowtype/recursive-code-config/commit/c736d86643f905fb7564a48e898939045bbe586e).
> 
> So, this PR was helpful, but I’ll close it now that things are solved. 
Thanks for the fix. You might want to update the image used in the readme as well :).

**Pull request closed without merging**
